import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'ms';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'ms')) {
      setLanguageState(savedLanguage);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  const value = {
    language,
    setLanguage,
    t,
  };

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

// Translation keys
const translations = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.exco_users': 'EXCO Users',
    'nav.programs': 'Program Management',
    'nav.status': 'Status Tracking',
    'nav.queries': 'Queries',
    'nav.report': 'Report',
    'nav.users': 'User Management',
    'nav.profile': 'Profile',
    'nav.navigation': 'Navigation',

    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.subtitle': 'Overview of program management activities',
    'dashboard.welcome': 'Welcome to Kedah Plan Hub',
    'dashboard.total_programs': 'Total Programs',
    'dashboard.payment_completed_programs': 'Payment Completed Programs',
    'dashboard.rejected_programs': 'Rejected Programs',
    'dashboard.pending_programs': 'Pending Programs',
    'dashboard.active_programs': 'Active Programs',
    'dashboard.completed_programs': 'Completed Programs',
    'dashboard.total_budget': 'Total Expense',
    'dashboard.remaining_budget': 'Remaining Budget',
    'dashboard.budget_used': 'Budget Used',
    'dashboard.budget_used_percentage': 'of total budget',
    'dashboard.recent_programs': 'Recent Programs',
    'dashboard.no_programs': 'No programs found',
    'dashboard.update_budget': 'Update Total Expense',
    'dashboard.update_budget_desc': 'Set the new total expense for all programs.',
    'dashboard.total_budget_rm': 'Total Expense (RM)',
    'dashboard.enter_budget': 'Enter total expense',
    'dashboard.update_budget_btn': 'Update Budget',
    'dashboard.available_for_programs': 'Available for programs',
    'dashboard.usage': 'Usage',
    'dashboard.used': 'used',
    'dashboard.budget_error': 'Budget must be greater than 0',
    'dashboard.budget_updated': 'Budget updated successfully!',
    'dashboard.budget_update_failed': 'Failed to update budget',
    'dashboard.budget_update_error': 'Failed to update budget. Please try again.',

    // Budget Management
    'budget.insufficient': 'Insufficient budget',
    'budget.exceeds_remaining': 'Program budget exceeds remaining budget',
    'budget.available': 'Budget available',
    'budget.remaining_after_program': 'remaining after this program',
    'budget.total_budget': 'Total Budget',
    'budget.remaining_budget': 'Remaining Budget',
    'budget.allocated_programs': 'Allocated Programs',
    'budget.program_budget': 'Program Budget',
    'budget.after_this_program': 'After This Program',
    'budget.cannot_create': 'Cannot create program: Budget exceeds remaining budget',
    'budget.create_program': 'Create new program',
    'budget.information': 'Budget Information',
    'budget.summary': 'Budget Summary',

    // Profile
    'profile.title': 'Profile',
    'profile.subtitle': 'Manage your account settings and preferences',
    'profile.photo': 'Profile Photo',
    'profile.photo_desc': 'Upload a new profile photo. The image should be at least 400x400 pixels.',
    'profile.change_photo': 'Change Photo',
    'profile.upload': 'Upload',
    'profile.uploading': 'Uploading...',
    'profile.reset': 'Reset',
    'profile.basic_info': 'Basic Information',
    'profile.full_name': 'Full Name',
    'profile.email': 'Email Address',
    'profile.phone': 'Phone Number',
    'profile.role': 'Role',
    'profile.account_status': 'Account Status',
    'profile.member_since': 'Member Since',
    'profile.update_profile': 'Update Profile',
    'profile.change_password': 'Change Password',
    'profile.password_desc': 'Ensure your account is using a long, random password to stay secure.',
    'profile.current_password': 'Current Password',
    'profile.new_password': 'New Password',
    'profile.confirm_password': 'Confirm New Password',
    'profile.password_help': 'Password must be at least 8 characters long.',
    'profile.change_password_btn': 'Change Password',

    // User Management
    'users.title': 'User Management',
    'users.subtitle': 'Manage system users and their roles',
    'users.add_user': 'Add User',
    'users.add_new_user': 'Add New User',
    'users.add_user_desc': 'Create a new user account for the system.',
    'users.name': 'Name',
    'users.email': 'Email',
    'users.phone': 'Phone Number',
    'users.password': 'Password',
    'users.role': 'Role',
    'users.status': 'Status',
    'users.actions': 'Actions',
    'users.edit': 'Edit',
    'users.delete': 'Delete',
    'users.active': 'Active',
    'users.inactive': 'Inactive',
    'users.enter_full_name': 'Enter full name',
    'users.enter_password': 'Enter password',
    'users.select_role': 'Select role',
    'users.fill_required_fields': 'Please fill in all required fields.',
    'users.added_successfully': 'User has been added successfully.',
    'users.add_failed': 'Failed to add user.',
    'users.updated_successfully': 'User has been updated successfully.',
    'users.update_failed': 'Failed to update user.',
    'users.deleted_successfully': 'User has been deleted successfully.',
    'users.delete_failed': 'Failed to delete user.',
    'users.status_updated': 'User status has been updated.',
    'users.status_update_failed': 'Failed to update user status.',
    'users.user_not_found': 'User not found.',
    'users.access_denied': 'Access Denied',
    'users.no_permission': 'You don\'t have permission to access this page.',
    'users.last_login': 'Last Login',

    // User Management additional translations
    'users.total_users': 'Total Users',
    'users.admins': 'Admins',
    'users.active_users': 'Active Users',
    'users.inactive_users': 'Inactive Users',
    'users.search_placeholder': 'Search users by name or email...',
    'users.all_roles': 'All Roles',
    'users.users_count': 'Users ({count})',

    // Dashboard additional translations
    'dashboard.welcome_back': 'Welcome back, {name}',
    'dashboard.overall_summary': 'Overall Summary',

    // Program Management
    'programs.title': 'Program Management',
    'programs.create_manage_desc': 'Create and manage programs',
    'programs.review_approve_desc': 'Review and approve programs',
    'programs.add_program': 'Add Program',
    'programs.create_new_program': 'Create New Program',
    'programs.create_program': 'Create Program',
    'programs.program_name': 'Program Name',
    'programs.enter_program_name': 'Enter program name',
    'programs.budget': 'Budget',
    'programs.budget_rm': 'Budget (RM)',
    'programs.enter_budget_amount': 'Enter budget amount',
    'programs.recipient': 'Recipient',
    'programs.recipient_name': 'Recipient Name',
    'programs.enter_recipient_name': 'Enter recipient name',
    'programs.status': 'Status',
    'programs.created_by': 'Created By',
    'programs.created_at': 'Created At',
    'programs.actions': 'Actions',
    'programs.view': 'View',
    'programs.edit': 'Edit',
    'programs.delete': 'Delete',
    'programs.submitted_by': 'Submitted By',
    'programs.documents': 'Documents',
    'programs.add_document': 'Add Document',
    'programs.document_name': 'Document Name',
    'programs.enter_document_name': 'Enter document name',
    'programs.file': 'File',
    'programs.fill_required_fields': 'Please fill all required fields',
    'programs.created_successfully': 'Program created successfully',
    'programs.created_with_docs': 'Program created successfully with {count} document(s) uploaded to database',
    'programs.partial_success': 'Partial Success',
    'programs.documents_failed': 'Program created but documents failed to upload',
    'programs.create_failed': 'Failed to create program',
    'programs.updated_successfully': 'Program updated successfully',
    'programs.update_failed': 'Failed to update program',
    'programs.submitted_for_review': 'Program submitted for review',
    'programs.submit_failed': 'Failed to submit program',
    'programs.payment_completed_successfully': 'Payment completed successfully',
    'programs.rejected': 'Program Rejected',
    'programs.rejected_successfully': 'Program has been rejected',
    'programs.query_sent': 'Query Sent',
    'programs.query_sent_desc': 'Query has been sent to EXCO PA',
    'programs.query_failed': 'Failed to send query',
    'programs.select_document': 'Please select a document to upload',
    'programs.document_added': 'Document added to program',
    'programs.document_uploaded': 'Document uploaded successfully',
    'programs.upload_failed': 'Failed to upload document',
    'programs.document_deleted': 'Document deleted successfully',
    'programs.delete_document_failed': 'Failed to delete document',
    'programs.no_program_selected': 'No program selected',
    'programs.finance_document_uploaded': 'Finance document uploaded successfully',
    'programs.upload_finance_failed': 'Failed to upload finance document',
    'programs.enter_query': 'Please enter a query',
    'programs.query_submitted': 'Query submitted successfully',
    'programs.query_submit_failed': 'Failed to submit query',
    'programs.enter_answer': 'Please enter an answer',
    'programs.no_query_selected': 'No query selected',
    'programs.query_answered': 'Query answered successfully',
    'programs.answer_query_failed': 'Failed to answer query',
    'programs.exco_letter_ref': 'EXCO Letter Reference Number',
    'programs.enter_reference_number': 'Enter reference number',

    // Status Tracking
    'status.title': 'Status Tracking',
    'status.subtitle': 'Monitor all program statuses and progress',
    'status.program': 'Program',
    'status.current_status': 'Current Status',
    'status.last_updated': 'Last Updated',
    'status.remarks': 'Remarks',
    'status.total_programs': 'Total Programs',
    'status.complete_can_send_to_mmk': 'Complete and can be sent to MMK office',
    'status.under_review_by_mmk': 'Under Review by MMK office',
    'status.document_accepted_by_mmk': 'Document Accepted by MMK Office',
    'status.payment_in_progress': 'Payment in Progress',
    'status.payment_completed': 'Payment Completed',
    'status.rejected': 'Rejected',
    'status.programs_overview': 'Programs Overview',
    'status.search_programs': 'Search programs...',
    'status.filter_by_status': 'Filter by status',
    'status.all_status': 'All Status',
    'status.draft': 'Draft',
    'status.under_review': 'Under Review',
    'status.query': 'Query',
    'status.query_answered': 'Query Answered',
    'status.letter_ref': 'Letter Ref',
    'status.voucher_no': 'Voucher No.',
    'status.eft_no': 'EFT No.',
    'status.showing': 'Showing',
    'status.to': 'to',
    'status.of': 'of',
    'status.results': 'results',

    // Queries
    'queries.title': 'Queries',
    'queries.management': 'Query Management',
    'queries.subtitle': 'Handle queries from Finance and update program details',
    'queries.ask_question': 'Ask a Question',
    'queries.question': 'Question',
    'queries.answer': 'Answer',
    'queries.answered': 'Answered',
    'queries.pending': 'Pending',
    'queries.submit': 'Submit',
    'queries.reply': 'Reply',
    'queries.active_queries': 'Active Queries',
    'queries.answered_queries': 'Answered Queries',
    'queries.total_programs': 'Total Programs with Queries',
    'queries.history': 'Query History',
    'queries.total_queries': 'Total Queries',
    'queries.provide_message': 'Please provide a query message',
    'queries.submitted_successfully': 'Query submitted successfully',
    'queries.submit_failed': 'Failed to submit query',
    'queries.provide_answer': 'Please provide an answer',
    'queries.answered_successfully': 'Query answered successfully',
    'queries.answer_failed': 'Failed to answer query',
    'queries.fill_required_fields': 'Please fill all required fields',
    'queries.program_updated': 'Program updated successfully',
    'queries.update_program_failed': 'Failed to update program',
    'queries.select_document': 'Please select a document to upload',
    'queries.no_program_selected': 'No program selected',
    'queries.document_uploaded': 'Document uploaded successfully',
    'queries.upload_failed': 'Failed to upload document',
    'queries.document_deleted': 'Document deleted successfully',
    'queries.delete_document_failed': 'Failed to delete document',

    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.close': 'Close',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.confirm': 'Confirm',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.logout': 'Logout',
    'common.updating': 'Updating...',
    'common.date': 'Date',

    // EXCO Users
    'exco.users.title': 'EXCO Users Directory',
    'exco.users.description': 'View all EXCO users and their contact information',
    'exco.users.count': 'users',
    'exco.users.empty': 'No EXCO users found',
    'exco.users.no_phone': 'No phone number',
    'exco.users.budgets': 'EXCO Users Budgets',
    'exco.users.manage_programs': 'Manage Programs',
    'exco.users.program_management': 'Program Management',
    'exco.users.back_to_exco_users': 'Back to EXCO Users',
    'exco.users.total_budget': 'Total Expense',
    'exco.users.remaining_budget': 'Remaining Budget',
    'exco.users.update_budget': 'Update Budget',
    'exco.users.budget_updated': 'Budget updated successfully',
    'exco.users.budget_update_failed': 'Failed to update budget',

    // Report
    'report.title': 'Report',
    'report.subtitle': 'Generate and download program reports',
    'report.generate_report': 'Generate Report',
    'report.download_report': 'Download Report',
    'report.select_date_range': 'Select Date Range',
    'report.start_date': 'Start Date',
    'report.end_date': 'End Date',
    'report.select_user': 'Select User',
    'report.all_users': 'All Users',
    'report.select_status': 'Select Status',
    'report.all_status': 'All Status',
    'report.approved': 'Approved',
    'report.rejected': 'Rejected',
    'report.both': 'Both',
    'report.report_generated': 'Report generated successfully',
    'report.report_failed': 'Failed to generate report',



    // Roles
    'role.admin': 'Administrator',
    'role.exco_user': 'EXCO User',
    'role.finance_mmk': 'Finance MMK',
    'role.finance_officer': 'Finance Officer',
    'role.super_admin': 'Super Admin',



    // Notifications
    'notifications.title': 'Notifications',
    'notifications.no_notifications': 'No notifications',
    'notifications.mark_all_read': 'Mark all as read',
    'notifications.clear_all': 'Clear all',

    // Language
    'language.english': 'English',
    'language.malay': 'Bahasa Malaysia',

    // EXCO User Dashboard additional translations
    'exco.dashboard.programs_for': 'Programs for {name}',
    'exco.dashboard.total_budget': 'Total Expense',
    'exco.dashboard.remaining_budget': 'Remaining Budget',
    'exco.dashboard.user_information': 'User Information',
    'exco.dashboard.recent_programs': 'Recent Programs',
    'exco.dashboard.no_recent_programs': 'No recent programs found for this user.',

    // Table column translations
    'table.name': 'Name',
    'table.email': 'Email',
    'table.phone': 'Phone',
    'table.role': 'Role',
    'table.status': 'Status',
    'table.created': 'Created',
    'table.actions': 'Actions',
    'table.total_programs': 'Total Programs',
    'table.pending_programs': 'Pending Programs',
    'table.total_budget': 'Total Expense',
    'table.remaining_budget': 'Remaining Budget',
    'table.view': 'View',

    // Timeline translations
    'timeline.status_timeline': 'Status Timeline',
    'timeline.draft': 'Draft',
    'timeline.under_review': 'Under Review',
    'timeline.query': 'Query',
    'timeline.query_answered': 'Query Answered',
    'timeline.complete_can_send_to_mmk': 'Send to MMK',
    'timeline.under_review_by_mmk': 'MMK Review',
    'timeline.document_accepted_by_mmk': 'Document Accepted',
    'timeline.payment_in_progress': 'Payment in Progress',
    'timeline.payment_completed': 'Payment Completed',
    'timeline.current': 'Current',
    'timeline.done': 'Done',
    'timeline.pending': 'Pending',
  },
  ms: {
    // Navigation
    'nav.dashboard': 'Papan Pemuka',
    'nav.exco_users': 'Pengguna EXCO',
    'nav.programs': 'Pengurusan Program',
    'nav.status': 'Penjejakan Status',
    'nav.queries': 'Pertanyaan',
    'nav.report': 'Laporan',
    'nav.users': 'Pengurusan Pengguna',
    'nav.profile': 'Profil',
    'nav.navigation': 'Navigasi',

    // Dashboard
    'dashboard.title': 'Papan Pemuka',
    'dashboard.subtitle': 'Gambaran keseluruhan aktiviti pengurusan program',
    'dashboard.welcome': 'Selamat Datang ke Kedah Plan Hub',
    'dashboard.total_programs': 'Jumlah Program',
    'dashboard.payment_completed_programs': 'Program Bayaran Selesai',
    'dashboard.rejected_programs': 'Program Ditolak',
    'dashboard.pending_programs': 'Program Menunggu',
    'dashboard.active_programs': 'Program Aktif',
    'dashboard.completed_programs': 'Program Selesai',
    'dashboard.total_budget': 'Perbelanjaan Keseluruhan',
    'dashboard.remaining_budget': 'Perbelanjaan Keseluruhan Baki',
    'dashboard.budget_used': 'Perbelanjaan Digunakan',
    'dashboard.budget_used_percentage': 'daripada jumlah perbelanjaan',
    'dashboard.recent_programs': 'Program Terkini',
    'dashboard.no_programs': 'Tiada program dijumpai',
    'dashboard.update_budget': 'Kemas Kini Jumlah Perbelanjaan Keseluruhan',
    'dashboard.update_budget_desc': 'Tetapkan jumlah perbelanjaan baharu untuk semua program.',
    'dashboard.total_budget_rm': 'Jumlah Perbelanjaan Keseluruhan (RM)',
    'dashboard.enter_budget': 'Masukkan jumlah perbelanjaan',
    'dashboard.update_budget_btn': 'Kemas Kini Perbelanjaan Keseluruhan',
    'dashboard.available_for_programs': 'Tersedia untuk program',
    'dashboard.usage': 'Penggunaan',
    'dashboard.used': 'digunakan',
    'dashboard.budget_error': 'Perbelanjaan mesti lebih besar daripada 0',
    'dashboard.budget_updated': 'Perbelanjaan berjaya dikemas kini!',
    'dashboard.budget_update_failed': 'Gagal mengemas kini perbelanjaan',
    'dashboard.budget_update_error': 'Gagal mengemas kini perbelanjaan. Sila cuba lagi.',

    // Budget Management
    'budget.insufficient': 'Perbelanjaan tidak mencukupi',
    'budget.exceeds_remaining': 'Perbelanjaan program melebihi perbelanjaan baki',
    'budget.available': 'Perbelanjaan tersedia',
    'budget.remaining_after_program': 'baki selepas program ini',
    'budget.total_budget': 'Jumlah Perbelanjaan',
    'budget.remaining_budget': 'Perbelanjaan Baki',
    'budget.allocated_programs': 'Program Diperuntukkan',
    'budget.program_budget': 'Perbelanjaan Program',
    'budget.after_this_program': 'Selepas Program Ini',
    'budget.cannot_create': 'Tidak boleh mencipta program: Perbelanjaan melebihi perbelanjaan baki',
    'budget.create_program': 'Cipta program baharu',
    'budget.information': 'Maklumat Perbelanjaan',
    'budget.summary': 'Ringkasan Perbelanjaan',

    // Profile
    'profile.title': 'Profil',
    'profile.subtitle': 'Urus tetapan akaun dan keutamaan anda',
    'profile.photo': 'Foto Profil',
    'profile.photo_desc': 'Muat naik foto profil baharu. Imej harus sekurang-kurangnya 400x400 piksel.',
    'profile.change_photo': 'Tukar Foto',
    'profile.upload': 'Muat Naik',
    'profile.uploading': 'Memuat Naik...',
    'profile.reset': 'Set Semula',
    'profile.basic_info': 'Maklumat Asas',
    'profile.full_name': 'Nama Penuh',
    'profile.email': 'Alamat E-mel',
    'profile.phone': 'Nombor Telefon',
    'profile.role': 'Peranan',
    'profile.account_status': 'Status Akaun',
    'profile.member_since': 'Ahli Sejak',
    'profile.update_profile': 'Kemas Kini Profil',
    'profile.change_password': 'Tukar Kata Laluan',
    'profile.password_desc': 'Pastikan akaun anda menggunakan kata laluan yang panjang dan rawak untuk kekal selamat.',
    'profile.current_password': 'Kata Laluan Semasa',
    'profile.new_password': 'Kata Laluan Baharu',
    'profile.confirm_password': 'Sahkan Kata Laluan Baharu',
    'profile.password_help': 'Kata laluan mesti sekurang-kurangnya 8 aksara.',
    'profile.change_password_btn': 'Tukar Kata Laluan',

    // User Management
    'users.title': 'Pengurusan Pengguna',
    'users.subtitle': 'Urus pengguna sistem dan peranan mereka',
    'users.add_user': 'Tambah Pengguna',
    'users.add_new_user': 'Tambah Pengguna Baharu',
    'users.add_user_desc': 'Cipta akaun pengguna baharu untuk sistem.',
    'users.name': 'Nama',
    'users.email': 'E-mel',
    'users.phone': 'Nombor Telefon',
    'users.password': 'Kata Laluan',
    'users.role': 'Peranan',
    'users.status': 'Status',
    'users.actions': 'Tindakan',
    'users.edit': 'Sunting',
    'users.delete': 'Padam',
    'users.active': 'Aktif',
    'users.inactive': 'Tidak Aktif',
    'users.enter_full_name': 'Masukkan nama penuh',
    'users.enter_password': 'Masukkan kata laluan',
    'users.select_role': 'Pilih peranan',
    'users.fill_required_fields': 'Sila isi semua medan yang diperlukan.',
    'users.added_successfully': 'Pengguna telah berjaya ditambah.',
    'users.add_failed': 'Gagal menambah pengguna.',
    'users.updated_successfully': 'Pengguna telah berjaya dikemas kini.',
    'users.update_failed': 'Gagal mengemas kini pengguna.',
    'users.deleted_successfully': 'Pengguna telah berjaya dipadam.',
    'users.delete_failed': 'Gagal memadam pengguna.',
    'users.status_updated': 'Status pengguna telah dikemas kini.',
    'users.status_update_failed': 'Gagal mengemas kini status pengguna.',
    'users.user_not_found': 'Pengguna tidak dijumpai.',
    'users.access_denied': 'Akses Ditolak',
    'users.no_permission': 'Anda tidak mempunyai kebenaran untuk mengakses halaman ini.',
    'users.last_login': 'Log Masuk Terakhir',

    // User Management additional translations
    'users.total_users': 'Jumlah Pengguna',
    'users.admins': 'Pentadbir',
    'users.active_users': 'Pengguna Aktif',
    'users.inactive_users': 'Pengguna Tidak Aktif',
    'users.search_placeholder': 'Cari pengguna berdasarkan nama atau e-mel...',
    'users.all_roles': 'Semua Peranan',
    'users.users_count': 'Pengguna ({count})',

    // Dashboard additional translations
    'dashboard.welcome_back': 'Selamat Datang Kembali, {name}',
    'dashboard.overall_summary': 'Ringkasan Keseluruhan',

    // Program Management
    'programs.title': 'Pengurusan Program',
    'programs.create_manage_desc': 'Cipta dan urus program',
    'programs.review_approve_desc': 'Semak dan lulus program',
    'programs.add_program': 'Tambah Program',
    'programs.create_new_program': 'Cipta Program Baharu',
    'programs.create_program': 'Cipta Program',
    'programs.program_name': 'Nama Program',
    'programs.enter_program_name': 'Masukkan nama program',
    'programs.budget': 'Bajet',
    'programs.budget_rm': 'Sumbangan (RM)',
    'programs.enter_budget_amount': 'Masukkan jumlah bajet',
    'programs.recipient': 'Penerima',
    'programs.recipient_name': 'Penerima',
    'programs.enter_recipient_name': 'Masukkan nama penerima',
    'programs.status': 'Status',
    'programs.created_by': 'Dicipta Oleh',
    'programs.created_at': 'Dicipta Pada',
    'programs.actions': 'Tindakan',
    'programs.view': 'Lihat',
    'programs.edit': 'Sunting',
    'programs.delete': 'Padam',
    'programs.submitted_by': 'Dihantar Oleh',
    'programs.documents': 'Dokumen',
    'programs.add_document': 'Tambah Dokumen',
    'programs.document_name': 'Nama Dokumen',
    'programs.enter_document_name': 'Masukkan nama dokumen',
    'programs.file': 'Fail',
    'programs.fill_required_fields': 'Sila isi semua medan yang diperlukan',
    'programs.created_successfully': 'Program berjaya dicipta',
    'programs.created_with_docs': 'Program berjaya dicipta dengan {count} dokumen dimuat naik ke pangkalan data',
    'programs.partial_success': 'Kejayaan Separa',
    'programs.documents_failed': 'Program dicipta tetapi dokumen gagal dimuat naik',
    'programs.create_failed': 'Gagal mencipta program',
    'programs.updated_successfully': 'Program berjaya dikemas kini',
    'programs.update_failed': 'Gagal mengemas kini program',
    'programs.submitted_for_review': 'Program dihantar untuk semakan',
    'programs.submit_failed': 'Gagal menghantar program',
    'programs.payment_completed_successfully': 'Lulus Bayaran Di MMK',
    'programs.rejected': 'Program Ditolak',
    'programs.rejected_successfully': 'Program telah ditolak',
    'programs.query_sent': 'Pertanyaan Dihantar',
    'programs.query_sent_desc': 'Pertanyaan telah dihantar kepada PA EXCO',
    'programs.query_failed': 'Gagal menghantar pertanyaan',
    'programs.select_document': 'Sila pilih dokumen untuk dimuat naik',
    'programs.document_added': 'Dokumen ditambah kepada program',
    'programs.document_uploaded': 'Dokumen berjaya dimuat naik',
    'programs.upload_failed': 'Gagal memuat naik dokumen',
    'programs.document_deleted': 'Dokumen berjaya dipadam',
    'programs.delete_document_failed': 'Gagal memadam dokumen',
    'programs.no_program_selected': 'Tiada program dipilih',
    'programs.finance_document_uploaded': 'Dokumen kewangan berjaya dimuat naik',
    'programs.upload_finance_failed': 'Gagal memuat naik dokumen kewangan',
    'programs.enter_query': 'Sila masukkan pertanyaan',
    'programs.query_submitted': 'Pertanyaan berjaya dihantar',
    'programs.query_submit_failed': 'Gagal menghantar pertanyaan',
    'programs.enter_answer': 'Sila masukkan jawapan',
    'programs.no_query_selected': 'Tiada pertanyaan dipilih',
    'programs.query_answered': 'Pertanyaan berjaya dijawab',
    'programs.answer_query_failed': 'Gagal menjawab pertanyaan',
    'programs.exco_letter_ref': 'No Rujukan Surat EXCO',
    'programs.enter_reference_number': 'Masukkan nombor rujukan',

    // Status Tracking
    'status.title': 'Penjejakan Status',
    'status.subtitle': 'Pantau semua status dan kemajuan program',
    'status.program': 'Program',
    'status.current_status': 'Status Semasa',
    'status.last_updated': 'Terakhir Dikemas Kini',
    'status.remarks': 'Ulasan',
    'status.total_programs': 'Jumlah Program',
    'status.complete_can_send_to_mmk': 'Lengkap dan boleh dihantar ke pejabat MMK',
    'status.under_review_by_mmk': 'Diperiksa oleh pejabat MMK',
    'status.document_accepted_by_mmk': 'Dokumen Diterima oleh Pejabat MMK',
    'status.payment_in_progress': 'Bayaran Sedang Berlangsung',
    'status.payment_completed': 'Lulus Bayaran Di MMK',
    'status.rejected': 'Ditolak',
    'status.programs_overview': 'Gambaran Keseluruhan Program',
    'status.search_programs': 'Cari program...',
    'status.filter_by_status': 'Tapis mengikut status',
    'status.all_status': 'Semua Status',
    'status.draft': 'Draf',
    'status.under_review': 'Sedang Diperiksa',
    'status.query': 'Pertanyaan',
    'status.query_answered': 'Query Dijawab',
    'status.letter_ref': 'Rujukan Surat',
    'status.voucher_no': 'No. Voucher',
    'status.eft_no': 'No. EFT',
    'status.showing': 'Menunjukkan',
    'status.to': 'kepada',
    'status.of': 'daripada',
    'status.results': 'hasil',

    // Queries
    'queries.title': 'Pertanyaan',
    'queries.management': 'Pengurusan Pertanyaan',
    'queries.subtitle': 'Urus pertanyaan daripada Kewangan dan kemas kini butiran program',
    'queries.ask_question': 'Ajukan Soalan',
    'queries.question': 'Soalan',
    'queries.answer': 'Jawapan',
    'queries.answered': 'Dijawab',
    'queries.pending': 'Menunggu',
    'queries.submit': 'Hantar',
    'queries.reply': 'Balas',
    'queries.active_queries': 'Pertanyaan Aktif',
    'queries.answered_queries': 'Query Dijawab',
    'queries.total_programs': 'Jumlah Program dengan Pertanyaan',
    'queries.history': 'Sejarah Pertanyaan',
    'queries.total_queries': 'Jumlah Pertanyaan',
    'queries.provide_message': 'Sila berikan mesej pertanyaan',
    'queries.submitted_successfully': 'Pertanyaan berjaya dihantar',
    'queries.submit_failed': 'Gagal menghantar pertanyaan',
    'queries.provide_answer': 'Sila berikan jawapan',
    'queries.answered_successfully': 'Pertanyaan berjaya dijawab',
    'queries.answer_failed': 'Gagal menjawab pertanyaan',
    'queries.fill_required_fields': 'Sila isi semua medan yang diperlukan',
    'queries.program_updated': 'Program berjaya dikemas kini',
    'queries.update_program_failed': 'Gagal mengemas kini program',
    'queries.select_document': 'Sila pilih dokumen untuk dimuat naik',
    'queries.no_program_selected': 'Tiada program dipilih',
    'queries.document_uploaded': 'Dokumen berjaya dimuat naik',
    'queries.upload_failed': 'Gagal memuat naik dokumen',
    'queries.document_deleted': 'Dokumen berjaya dipadam',
    'queries.delete_document_failed': 'Gagal memadam dokumen',

    // Common
    'common.loading': 'Memuat...',
    'common.error': 'Ralat',
    'common.success': 'Berjaya',
    'common.cancel': 'Batal',
    'common.save': 'Simpan',
    'common.delete': 'Padam',
    'common.edit': 'Sunting',
    'common.view': 'Lihat',
    'common.close': 'Tutup',
    'common.yes': 'Ya',
    'common.no': 'Tidak',
    'common.confirm': 'Sahkan',
    'common.back': 'Kembali',
    'common.next': 'Seterusnya',
    'common.previous': 'Sebelumnya',
    'common.logout': 'Log Keluar',
    'common.updating': 'Mengemas Kini...',
    'common.date': 'Tarikh',

    // EXCO Users
    'exco.users.title': 'Direktori Pengguna EXCO',
    'exco.users.description': 'Lihat semua pengguna EXCO dan maklumat hubungan mereka',
    'exco.users.count': 'pengguna',
    'exco.users.empty': 'Tiada pengguna EXCO dijumpai',
    'exco.users.no_phone': 'Tiada nombor telefon',
    'exco.users.budgets': 'Bajet Pengguna EXCO',
    'exco.users.manage_programs': 'Urus Program',
    'exco.users.program_management': 'Pengurusan Program',
    'exco.users.back_to_exco_users': 'Kembali kepada Pengguna EXCO',
    'exco.users.total_budget': 'Jumlah Perbelanjaan Keseluruhan',
    'exco.users.remaining_budget': 'Perbelanjaan Keseluruhan Baki',
    'exco.users.update_budget': 'Kemas Kini Bajet',
    'exco.users.budget_updated': 'Bajet berjaya dikemas kini!',
    'exco.users.budget_update_failed': 'Gagal mengemas kini bajet',

    // Report
    'report.title': 'Laporan',
    'report.subtitle': 'Jana dan muat turun laporan program',
    'report.generate_report': 'Jana Laporan',
    'report.download_report': 'Muat Turun Laporan',
    'report.select_date_range': 'Pilih Julat Tarikh',
    'report.start_date': 'Tarikh Mula',
    'report.end_date': 'Tarikh Tamat',
    'report.select_user': 'Pilih Pengguna',
    'report.all_users': 'Semua Pengguna',
    'report.select_status': 'Pilih Status',
    'report.all_status': 'Semua Status',
    'report.approved': 'Diluluskan',
    'report.rejected': 'Ditolak',
    'report.both': 'Kedua-duanya',
    'report.report_generated': 'Laporan berjaya dijana',
    'report.report_failed': 'Gagal menjana laporan',



    // Roles
    'role.admin': 'Pentadbir',
    'role.exco_user': 'Pengguna EXCO',
    'role.finance_mmk': 'Kewangan MMK',
    'role.finance_officer': 'Pegawai Kewangan',
    'role.super_admin': 'Pentadbir Super',



    // Notifications
    'notifications.title': 'Pemberitahuan',
    'notifications.no_notifications': 'Tiada pemberitahuan',
    'notifications.mark_all_read': 'Tandakan semua sebagai dibaca',
    'notifications.clear_all': 'Kosongkan semua',

    // Language
    'language.english': 'English',
    'language.malay': 'Bahasa Malaysia',

    // EXCO User Dashboard additional translations
    'exco.dashboard.programs_for': 'Program untuk {name}',
    'exco.dashboard.total_budget': 'Jumlah Perbelanjaan Keseluruhan',
    'exco.dashboard.remaining_budget': 'Perbelanjaan Keseluruhan Baki',
    'exco.dashboard.user_information': 'Maklumat Pengguna',
    'exco.dashboard.recent_programs': 'Program Terkini',
    'exco.dashboard.no_recent_programs': 'Tiada program terkini ditemui untuk pengguna ini.',

    // Table column translations
    'table.name': 'Nama',
    'table.email': 'E-mel',
    'table.phone': 'Nombor Telefon',
    'table.role': 'Peranan',
    'table.status': 'Status',
    'table.created': 'Dicipta',
    'table.actions': 'Tindakan',
    'table.total_programs': 'Jumlah Program',
    'table.pending_programs': 'Program Menunggu',
    'table.total_budget': 'Jumlah Perbelanjaan Keseluruhan',
    'table.remaining_budget': 'Perbelanjaan Keseluruhan Baki',
    'table.view': 'Lihat',

    // Timeline translations
    'timeline.status_timeline': 'Status Timeline',
    'timeline.draft': 'Draf',
    'timeline.under_review': 'Diperiksa',
    'timeline.query': 'Query',
    'timeline.query_answered': 'Query Dijawab',
    'timeline.complete_can_send_to_mmk': 'Hantar ke MMK',
    'timeline.under_review_by_mmk': 'Semakan MMK',
    'timeline.document_accepted_by_mmk': 'Dokumen Diterima',
    'timeline.payment_in_progress': 'Bayaran Sedang Berlangsung',
    'timeline.payment_completed': 'Lulus Bayaran Di MMK',
    'timeline.current': 'Semasa',
    'timeline.done': 'Selesai',
    'timeline.pending': 'Menunggu',
  },
}; 